name: AsRelegion
version: '${version}'

depend: [MMOCore, MythicLib]

main: org.asyn.asRelegion.Main
api-version: '1.21'

commands:
  religionadmin:
    description: Admin Command
    permission: assreligion.admin
  religion:
    description: Player Command
    permission: assreligion.player